### ISSUE TITLE
when upload_to is specified, i am unable to know when file attributes are written

### ISSUE THREAD

**Issue by mkoryak** [panta/mongoose-file#1]
I was uploading some files, and on post my code looked roughly like this:

//model:
UserImageSchema.plugin(filePlugin, {
    name: "image",
    upload_to: make_upload_to_model(uploadsBase, 'portfolio'),
    relative_to: uploadsBase
});

//controller:
      if(req.files && req.files.file){
            _.each(req.files, function(file){
                var userImage = new db.UserImage({
                    name: file.name,
                });
                userImage.set('image.file', file);
                userImage.user = user._id;
                userImage.save(function(err){
                   if(err){
                       console.log("Couldnt save userImage", err);
                       res.send(500);
                   } else {
                       res.send({
                           fileId: userImage.id,
                           name: userImage.name
                       });
                   }
                });
            });
        } else {
            res.send(404);
        }

the problem is that when the file is moved, this is done async, and then the path is marked modified but the object is never saved. My 'userImage.save' function finished before the file was moved, so the file attributes were modified but never saved.

Moreover, i have no way to know when the move finishes so i cannot wait for it in my code. I am a mongo noob though, so maybe you know a way

**Comment by panta** [comment]
On Sat, Nov 24, 2012 at 3:51 PM, Misha notifications@github.com wrote:

> the problem is that when the file is moved, this is done async, and then
> the path is marked modified but the object is never saved. My
> 'userImage.save' function finished before the file was moved, so the file
> attributes were modified but never saved.
> 
> Moreover, i have no way to know when the move finishes so i cannot wait
> for it in my code. I am a mongo noob though, so maybe you know a way
> 
> the plugin has a `change_cb` option that you could use to be notified of
> changes to the file `path` value.

You could use it with some like the following:

UserImageSchema.plugin(filePlugin, {
  name: "image",
  upload_to: make_upload_to_model(uploadsBase, 'portfolio'),
  relative_to: uploadsBase,
  change_cb: function (fieldPathname, newPath, oldPath) {
    if (newPath || this.isModified()) {
      this.save(function(err) {
        if (err) {
          console.log("Couldnt save UserImage:", err);
        } else {
          console.log("UserImage saved.");
        }
    }
  }
});

Note that with this solution as is, when you return from your controller,
the view is rendered asynchronously with the final model save, so if you
rely on the file to be in its final place, you either need some sort of
async check in the view (using AJAX for example) or you need to move the
view rendering in the change_cb function (for example by attaching a
rendering callback to the document instance in your controller and checking
it in the change_cb function). If you can envision a simpler method, I'd
love to add it to the plugin though, so let me know!

Cheers,
Marco

 —

> Reply to this email directly or view it on GitHubhttps://github.com/panta/mongoose-file/issues/1.

## 

Marco Pantaleoni
